import type { Metadata } from "next";
import NavBar from "./components/topSide/NavBar";
import { Provider } from "../ui/provider";
import { Box, Grid } from "@chakra-ui/react";
import TodoContextProvider from "./context/TodoContext";

export const metadata: Metadata = {
  title: "Task Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <TodoContextProvider>
            <Grid w={{md: '25rem'}} mx={{ base: '1rem', md: 'auto' }} >
              <NavBar />
              {children}
            </Grid>
          </TodoContextProvider>
        </Provider>
      </body>
    </html>
  );
}
